name: Update Wallpaper Daily

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---- checkout repo ----
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---- setup python ----
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ---- install requirements ----
      - name: Install dependencies
        run: pip install -r requirements.txt

      # ---- run generator ----
      - name: Run script
        run: python generate.py

      # ---- commit new wallpaper ----
      - name: Commit updated image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add output-*.jpg
          git commit -m "daily wallpaper update" || echo "No changes"

          git push
